### ISSUE TITLE
missing threeStates.shp Shapefile

### ISSUE THREAD

**Issue by TheGuern** [jessnicwelch/edwebinar_mar19#1]
in the supplemental  Load Data section, we have this:

  threeStates     <- readOGR("./data/threeStates.shp")

, we never saved the threeStates SpatialPolygonsDataFrame to a .shp file to the data, or any other  folder; something like this?:

```
class(threeStates)
writeOGR(obj=threeStates, dsn="tempdir", layer="threeStates", driver="ESRI Shapefile") # this is in geographical projection
```

**Comment by jessnicwelch** [comment]
Hi. I'm sorry that I never saw this message! The file is in the ~/data directory. I suggest that you ensure your file paths and working directory are written/configured correctly.
